// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupaWebApi.Models;

#nullable disable

namespace SupaWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230812072510_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupaWebApi.Models.NetworkConfiguration", b =>
                {
                    b.Property<string>("NetworkLabelName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Networkcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NetworkLabelName");

                    b.ToTable("NetworkConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
